Feat/metadata
equinor/pepm-ui pull request #173
Opened 2023-11-24 07:51 UTC by mheggelund

2023-11-24 08:49 UTC, Sinrefvol requested changes
In some situations it is fine to start turning TS lint rules off, because one rule does not fit all the situations.

However, before turning off `/* eslint-disable max-lines */` and
`/* eslint-disable max-lines-per-function */`, think what can be improved here. Sometimes, things can be rewritten in a cleaner way, or written to be reusable functions/components

2023-11-24 08:49 UTC, Sinrefvol commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.tsx
> +              </Table.Cell>
Should be a reusable component, considering you are using almost the same code 3 times in total

2023-11-24 08:49 UTC, Sinrefvol commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.tsx
> +              </Table.Cell>
Reusable component

2023-11-24 08:49 UTC, Sinrefvol commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.tsx
> +              </Table.Cell>
Reusable component

2023-11-24 08:49 UTC, Sinrefvol commented on src/pages/Browse/Browse.tsx
> +    });
use [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) function

2023-11-24 08:49 UTC, Sinrefvol commented on src/pages/Browse/Browse.tsx
> +    });
ex: 
```js
var zones = metadata.zone?.map(x=>({ metadataId: x.metadataId }));
metadataList.push(...zones)
```

2023-11-24 08:49 UTC, Sinrefvol commented on src/pages/Browse/Browse.tsx
> +    });
Same as previous. Make a reusable function that can be used for all situations.

2023-11-24 09:44 UTC, mheggelund commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.tsx
> +              </Table.Cell>
Fixed

2023-11-24 09:44 UTC, mheggelund commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.tsx
> +              </Table.Cell>
Fixed

2023-11-24 10:54 UTC, mheggelund commented on src/pages/Browse/Browse.tsx
> +    });
Agree! Fixed.

2023-11-24 10:54 UTC, mheggelund commented on src/pages/Browse/Browse.tsx
> +    });
Fixed.

2023-11-27 11:00 UTC, Sinrefvol approved these changes

2023-11-28 08:07 UTC, merged