fix: Refactor AreaCoordinates, replace useEffect.
equinor/pepm-ui pull request #209
Opened 2024-01-25 12:57 UTC by mheggelund

2024-01-26 09:57 UTC, Sinrefvol requested changes

2024-01-26 09:57 UTC, Sinrefvol commented on src/components/AreaCoordinates/AreaCoordinates.tsx
> +  const setCoordinates = (target: any, index: number, axis: string) => {
Better avoid using any. Slippery slope

2024-01-26 10:14 UTC, mheggelund commented on src/components/AreaCoordinates/AreaCoordinates.tsx
> +  const setCoordinates = (target: any, index: number, axis: string) => {
Korleis kan en løse den da, har Input target en type? Får bare TS error om en prøva nåke anna?

2024-01-30 11:49 UTC, Sinrefvol commented on src/components/AreaCoordinates/AreaCoordinates.tsx
> +  const setCoordinates = (target: any, index: number, axis: string) => {
Det kommer an på hva din target er da

2024-01-31 07:11 UTC, mheggelund commented on src/components/AreaCoordinates/AreaCoordinates.tsx
> +  const setCoordinates = (target: any, index: number, axis: string) => {
fixed

2024-01-31 08:34 UTC, Sinrefvol requested changes

2024-01-31 08:34 UTC, Sinrefvol commented on src/components/AreaCoordinates/AreaCoordinates.tsx
> +  const setCoordinates = (valute: string, index: number, axis: string) => {
Typo : valute instead of value

2024-01-31 09:01 UTC, mheggelund commented on src/components/AreaCoordinates/AreaCoordinates.tsx
> +  const setCoordinates = (valute: string, index: number, axis: string) => {
fixed

2024-01-31 09:14 UTC, merged