Refactor/object results
equinor/pepm-ui pull request #215
Opened 2024-01-30 08:50 UTC by mheggelund

2024-01-30 11:57 UTC, Sinrefvol requested changes

2024-01-30 11:57 UTC, Sinrefvol commented on src/hooks/useFetchResultts.ts
Typo in file name

2024-01-30 14:38 UTC, mheggelund commented on src/hooks/useFetchResultts.ts
fixed!

2024-01-31 08:35 UTC, Sinrefvol approved these changes

2024-01-31 08:54 UTC, merged