feat: First iteration of TopBar
equinor/pepm-ui pull request #25
Opened 2023-03-28 12:48 UTC by olavis

## First iteration of TopBar
This first iteration has no state or active links, looks like this:
<img width="1166" alt="Screenshot 2023-03-28 at 14 35 28" src="https://user-images.githubusercontent.com/38139899/228237719-77fb18cc-b7a9-4675-8f80-a4a319d2d041.png">

Resolves #24

2023-03-28 15:30 UTC, o-jorgensen requested changes
First review! Feel free to dismiss stupid suggestions, or discuss details anytime 😊

![image](https://user-images.githubusercontent.com/73646636/228289326-b5257ae2-34d6-45e1-a0ef-35560d441cf7.png)

2023-03-28 15:30 UTC, o-jorgensen commented on src/components/AppBar.tsx
> +  }
These can also be removed if we use the default height.

2023-03-28 15:30 UTC, o-jorgensen commented on src/components/AppBar.tsx
> +  height: inherit;
This can also be removed if we use the default height.

2023-03-28 15:30 UTC, o-jorgensen commented on src/index.css
> +  font-family: 'Equinor Mono', source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace !important;
`!important` — the root of all evil, and eternal nemesis in the specificity wars... 😋 We should use it sparingly.

2023-03-29 07:59 UTC, olavis commented on src/components/AppBar.tsx
> +
Nice!

2023-03-29 12:56 UTC, olavis commented on src/components/AppBar.tsx
> +  }
Yep!

2023-03-29 12:59 UTC, olavis commented on src/components/AppBar.tsx
> +`
Can remove `min-height`, but I'll need the others(i think??) to prevent spacing between the app bar line and the border/underline on active tab.

2023-03-29 13:00 UTC, olavis commented on src/components/AppBar.tsx
> +  height: inherit;
Need `flex` for `flex-end`, but I can remove height inherits 😄

2023-03-29 13:01 UTC, olavis commented on src/index.css
> +  font-family: 'Equinor Mono', source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace !important;
Removed 🫡

2023-03-29 14:47 UTC, merged