feat: Add GDE select Dialog.
equinor/pepm-ui pull request #293
Opened 2024-06-06 11:58 UTC by mheggelund

2024-06-06 12:03 UTC, mheggelund commented
Får ikke til å lagre som draft. Den er ikkje heilt klar enda. Alt av funksjonalitet ser ut til å virke, men mangler litt rydding og styling.

2024-06-10 07:01 UTC, Sinrefvol requested changes

2024-06-10 07:01 UTC, Sinrefvol commented on src/components/GrossDepositionEnviroment/GrossDepositionEnviromentGroup/GrossDepositionEnviromentGroup.tsx
> +        <Dialog.Header>Add stratigraphic column</Dialog.Header>
"Add GDE" is the correct one

2024-06-10 08:32 UTC, mheggelund commented on src/components/GrossDepositionEnviroment/GrossDepositionEnviromentGroup/GrossDepositionEnviromentGroup.tsx
> +                    <Icon data={deleteIcon} title={'Delete strat column row'} />
Fixed!

2024-06-10 08:32 UTC, mheggelund commented on src/components/GrossDepositionEnviroment/GrossDepositionEnviromentGroup/GrossDepositionEnviromentGroup.tsx
> +        <Dialog.Header>Add stratigraphic column</Dialog.Header>
Fixed!

2024-06-10 08:42 UTC, Sinrefvol approved these changes

2024-06-10 08:42 UTC, merged