Feat/model page
equinor/pepm-ui pull request #89
Opened 2023-09-18 12:11 UTC by mheggelund

Closes #61 closes #62

2023-09-18 13:55 UTC, olavis requested changes
I made some comments, but many of them can be resolved later in separate PRs. It's running and already an improvement compared to `main`, so I think we should fix what's most important and save the nitpicking for later. 😄

2023-09-18 13:55 UTC, olavis commented on src/pages/Compute/Compute.tsx
> +    <div>
Sometimes it's sufficient to just use fragments:
`<>{children}</>` 
instead of divs: 
`<div>{children}</div>`
I'd rather use fragment if you don't need to style children, since divs make objects more nested and affects tab navigation, screen readers etc. The div has some built-in styling compared to the empty fragment, but I haven't checked if they style the object identical in this case, and/or if you could achieve the same goal by styling the paragraph directly, or to style the wrapper in the parent instead (`SidebarWrapper` in this case).

2023-09-18 13:55 UTC, olavis commented on src/pages/Results/Results.tsx
> +      <p>Resukts for models here!</p>
Resukts fro mdoles rehe 🤌🏼

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelNameFrame/ModelNameFrame.styled.tsx
> +  background-color: rgb(247, 247, 247, 1);
I think this is equal to `tokens.colors.ui.background__light`, figma says:
<img width="255" alt="image" src="https://github.com/equinor/pepm-ui/assets/38139899/447d01e7-f14e-4682-8235-f2edb8c31897">
We haven't added it to `tokens/theme.ts` yet, but perhaps we could? 🤗

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelNavigationBar/ModelNavigationBar.tsx
> +            active={m.href === tab[tab.length - 1] ? true : false}
🪄 This should do exactly the same:
```suggestion
            active={m.href === tab[tab.length - 1]}
```

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelNavigationBar/ModelNavigationBar.tsx
Nice and clean, good! 🥳

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.tsx
> +      return await fetchModel({
This is probably my mistake, but we don't need `await` when we use `.then()`. I guess we can just leave it for now, since we're replacing the useEffect anyway 😅

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.tsx
I think we should consider merging this file (or parts of it) with `ModelMetadata.tsx`, they have much in common. 🤔

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelImageView/ModelImageView.tsx
Maybe we could make this a common component that we can re-use? (move to components folder and take image and text as prop). It doesn't seem to be domain specific. 😄

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelImageView/ModelImageView.tsx
> +import * as Styled from './ModelImageView.syled'
syled 🤓

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelSourceView/ModelSourceView.tsx
This too could perhaps be merged with `ModelInputFilesTable.tsx` 😊

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelView.styled.tsx
> +    margin-top: 12px;
```suggestion
    margin-top: ${spacings.MEDIUM_SMALL};
```

2023-09-18 13:55 UTC, olavis commented on src/features/ModelView/ModelView.styled.tsx
Nitpicking: many hardcoded px sizes here, is it possible to make the styling more responsive? (kudos for using `@media` though 👏)

2023-09-18 14:01 UTC, olavis commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.tsx
#90

2023-09-19 06:23 UTC, mheggelund commented on src/features/ModelView/ModelImageView/ModelImageView.tsx
Agree.

2023-09-19 06:28 UTC, mheggelund commented on src/features/ModelView/ModelMetadataView/ModelMetadataView.styled.tsx
Agree.

2023-09-19 08:28 UTC, mheggelund commented on src/features/ModelView/ModelNameFrame/ModelNameFrame.styled.tsx
> +  background-color: rgb(247, 247, 247, 1);
#91

2023-09-19 08:35 UTC, mheggelund commented on src/features/ModelView/ModelImageView/ModelImageView.tsx
#92

2023-09-19 08:39 UTC, mheggelund commented on src/features/ModelView/ModelView.styled.tsx
#93

2023-09-19 09:11 UTC, olavis commented on src/features/ModelView/ModelSourceView/ModelSourceView.tsx
#94

2023-09-19 09:13 UTC, olavis commented on src/features/ModelView/ModelSourceView/ModelSourceView.tsx
> +  // Add uploaded by and upload time
Create issue?

2023-09-19 09:16 UTC, olavis commented on src/features/ModelView/ModelSourceView/ModelSourceView.tsx
> +            model.fileUploads?.map((file: any) => (
Try not to use type `any`. We could leave it like this temporarily if we're doing #94 though.

2023-09-19 09:19 UTC, olavis commented on src/features/ModelView/ModelSourceView/ModelSourceView.tsx
> +          model.fileUploads?.length > 0 ? (
I think this could be shortened to `model.fileUploads?.length > 0 && model.fileUploads.map...`

2023-09-19 09:23 UTC, olavis commented on src/features/ModelView/ModelImageView/ModelImageView.styled.tsx
> +  border-color: #cdcdcd;
This could be added to theme as well, `tokens.colors.ui.background__medium` (ref #91)

2023-09-19 09:23 UTC, mheggelund commented on src/features/ModelView/ModelSourceView/ModelSourceView.tsx
> +  // Add uploaded by and upload time
#95

2023-09-19 09:28 UTC, mheggelund commented on src/features/ModelView/ModelImageView/ModelImageView.tsx
> +  // Load image and text from results
#96

2023-09-19 10:17 UTC, mheggelund commented on src/features/ModelView/ModelSourceView/ModelSourceView.tsx
> +          model.fileUploads?.length > 0 ? (
![image](https://github.com/equinor/pepm-ui/assets/98742460/f18bfc5a-fde6-4c67-b5bc-ca441d5589a1)

2023-09-19 10:19 UTC, olavis approved these changes

2023-09-19 10:19 UTC, merged